### ISSUE TITLE
api/v1beta1/dashboard_list.go strange file name

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#24]
When looking at the functions inside dashboard_list.go i notice that they are general purpose for the whole v1beta1 package.
We should probably change it's name to make it a bit easier to understand that.

And we should write it using more generic variables to show that it's generic used by multiple controllers.

**Comment by pb82** [comment]
resolved in #37

**Comment by HubertStefanski** [comment]
@NissesSenap Seems like you closed and reopened it on the same day? was this intended?

**Comment by NissesSenap** [comment]
Yes, this was in a PR that was abandoned so i don't think it's fixed yet.
